const trinkets = {
    phb: [
        'a mummified goblin hand.',
        'a piece of crystal that faintly glows in the moonlight.',
        'a gold coin minted in an unknown land.',
        'a diary written in a language you don’t know.',
        'a brass ring that never tarnishes.',
        'an old chess piece made from glass.',
        'a pair of knucklebone dice, each with a skull on the side that would normally show six pips.',
        'a small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it.',
        'a rope necklace from which dangles four mummified elf fingers.',
        'the deed for a parcel of land in a realm unknown to you.',
        'a 1-ounce block made from an unknown material.',
        'a small, cloth doll skewered with needles.',
        'a tooth from an unknown beast, an enormous scale, perhaps from a dragon.',
        'a bright green feather.',
        'an old divination card bearing your likeness.',
        'a glass orb filled with moving smoke.',
        'a 1-pound egg with a bright red shell.',
        'a pipe that blows bubbles.',
        'a glass jar containing a weird bit of flesh floating in pickling fluid.',
        'a tiny gnome-crafted music box that plays a song you dimly remember from your childhood.',
        'a small wooden statuette of a smug halfling.',
        'a brass orb etched with strange runes.',
        'a multicolored stone disk.',
        'a tiny silver icon of a raven.',
        'a bag containing forty-seven humanoid teeth, one of which is rotten.',
        'a shard of obsidian that always feels warm to the touch.',
        'a dragon’s bony talon hanging from a plain leather necklace.',
        'a pair of old socks.',
        'a blank book whose pages refuse to hold ink, chalk, graphite, or any other substance for marking.',
        'a silver badge in the shape of a five-pointed star.',
        'a knife that belonged to a relative.',
        'a glass vial filled with nail clippings.',
        'a rectangular metal device with two tiny metal cups on one end that throws sparks when wet.',
        'a white, sequined glove sized for a human.',
        'a vest with one hundred tiny pockets.',
        'a small, weightless stone block.',
        'a tiny sketch portrait of a goblin.',
        'an empty glass vial that smells of perfume when opened.',
        'a gemstone that looks like a lump of coal when examined by anyone but you.',
        'a scrap of cloth from an old banner.',
        'a rank insignia from a lost legionnaire.',
        'a tiny silver bell without a clapper.',
        'a mechanical canary inside a gnomish lamp.',
        'a tiny chest carved to look like it has numerous feet on the bottom.',
        'a dead sprite inside a clear glass bottle.',
        'a metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice).',
        'a glass orb filled with water, in which swims a clockwork goldfish.',
        'a silver spoon with an M engraved on the handle.',
        'a whistle made from gold-colored wood.',
        'a dead scarab beetle the size of your hand.',
        'two toy soldiers, one with a missing head.',
        'a small box filled with different-sized buttons.',
        'a candle that can’t be lit.',
        'a tiny cage with no door.',
        'an old key.',
        'an indecipherable treasure map.',
        'a hilt from a broken sword.',
        'a rabbit’s foot.',
        'a glass eye.',
        'a cameo carved in the likeness of a hideous person.',
        'a silver skull the size of a coin.',
        'an alabaster mask.',
        'a pyramid of sticky black incense that smells very bad.',
        'a nightcap that, when worn, gives you pleasant dreams.',
        'a single caltrop made from bone.',
        'a gold monocle frame without the lens.',
        'a 1-inch cube, each side painted a different color.',
        'a crystal knob from a door.',
        'a small packet filled with pink dust.',
        'a fragment of a beautiful song, written as musical notes on two pieces of parchment.',
        'a silver teardrop earring made from a real teardrop.',
        'the shell of an egg painted with scenes of human misery in disturbing detail.',
        'a fan that, when unfolded, shows a sleeping cat.',
        'a set of bone pipes.',
        'a four-leaf clover pressed inside a book discussing manners and etiquette.',
        'a sheet of parchment upon which is drawn a complex mechanical contraption.',
        'an ornate scabbard that fits no blade you have found so far.',
        'an invitation to a party where a murder happened.',
        'a bronze pentacle with an etching of a rat’s head in its center.',
        'a purple handkerchief embroidered with the name of a powerful archmage.',
        'half of a floorplan for a temple, castle, or some other structure.',
        'a bit of folded cloth that, when unfolded, turns into a stylish cap.',
        'a receipt of deposit at a bank in a far-flung city.',
        'a diary with seven missing pages.',
        'an empty silver snuffbox bearing an inscription on the surface that says “dreams”.',
        'an iron holy symbol devoted to an unknown god.',
        'a book that tells the story of a legendary hero’s rise and fall, with the last chapter missing.',
        'a vial of dragon blood.',
        'an ancient arrow of elven design.',
        'a needle that never bends.',
        'an ornate brooch of dwarven design.',
        'an empty wine bottle bearing a pretty label that says “The Wizard of Wines Winery, Red Dragon Crush, 331422-W”.',
        'A mosaic tile with a multicolored, glazed surface.',
        'a petrified mouse.',
        'a black pirate flag adorned with a dragon’s skull and crossbones.',
        'a tiny mechanical crab or spider that moves about when it’s not being observed.',
        'a glass jar containing lard with a label that reads “Griffon Grease”.',
        'a wooden box with a ceramic bottom that holds a living worm with a head on each end of its body.',
        'a metal urn containing the ashes of a hero'
    ],
    ee: [
        'a compass that always points to Mulmaster.',
        'a paper fan that won’t produce a breeze no matter how hard it’s waved.',
        'a petrified potato that resembles someone important to you.',
        'a glass cup that can only be filled halfway no matter how much liquid is poured into it.',
        'a mirror that shows only the back of your head.',
        'a small glass bird that, when set down near water, dips its head in as if to get a drink.',
        'a lady’s coin purse containing two sharp fangs.',
        'a small sea conch with the words “From the beginning” painted on the lip.',
        'a frost-covered silver locket that’s frozen shut.',
        'a seal which imprints a mysterious, unknown coat of arms into hard rock.',
        'a small handmirror that only reflects inanimate objects.',
        'a glass eyeball that looks about of its own accordance, and can roll around.',
        'a glass orb that replicates yesterday’s weather inside itself.',
        'a drinking cup that randomly fills with fresh or salt water, refilling once emptied.',
        'a deep blue piece of flint that, when struck, produces not a spark but a drop of water.',
        'a conch shell which is always damp and constantly drips saltwater.',
        'a charred, half-melted pewter clasp that glows as if smoldering but releases no heat.',
        'a clockwork finch that flaps its wings in the presence of a breeze.',
        'an unbreakable sealed jar of glowing water that hums when shaken.',
        'a small, finely polished geode whose crystals slowly fade between every color of the spectrum.',
        'a rough stone eye pulled from a petrified creature.',
        'a stone smoking pipe that never needs lighting.',
        'a small whistle that, when blown, whispers the name of a person or place unknown to you.',
        'a fist sized rock that “beats” like a heart.',
        'a pair of bronze scissors in the shape of a pair of leaping dolphins.',
        'a bronze oil lamp that is rumored to have once held a genie.',
        'a single gauntlet inscribed with a fire motif and an unfamiliar name in Primordial.',
        'a one-eyed little fish inside a spherical vial, much bigger than the vial’s neck, he has a cunning look.',
        'the tiny skull of a rabbit that whispers scathing insults when nobody is looking.',
        'a rag doll in the likeness of an owlbear.',
        'the dessicated body of a small, eight-legged black lizard.',
        'a small toy boat made with a walnut shell, toothpick, and a piece of cloth.',
        'a small pocket mirror that slowly fogs over while held.',
        'wind chimes that glow when the wind blows.',
        'a small, clay square with an unknown rune etched into one side.',
        'a tea kettle that heats itself when filled with water.',
        'an old scratched monocle which shows an underwater landscape whenever someone looks through it.',
        'a rose carved from coral.',
        'a set of dice with elemental symbols and primordial runes instead of pips or numbers.',
        'an amulet filled with liquid that churns, freezes or boils to match its wearer’s mood.',
        'a small silver bell that makes a sound like quiet, distant thunder when it’s struck.',
        'a small vial of black sand that glows slightly in the moonlight.',
        'a small whale tooth etched with an image of waves crashing upon a beach.',
        'an hourglass in which the sands pour upward instead of downward.',
        'a glass pendant with a hole in the center that a mild breeze always blows out of.',
        'a soft feather that falls like a stone when dropped.',
        'a large transparent gem that, when gripped tightly, whispers in Terran.',
        'a small crystal snowglobe that, when shaken, seems to form silhouettes of dancing forms.',
        'half of a palm-sized geode that pulses dimly with purple light.',
        'a book filled with writing that only appears when the book is held underwater.',
        'a sealed envelope made of red leather that you haven’t been able to open, it smells of campfire.',
        'a locket of hair that is rumored to have come from a famed fire genasi.',
        'flint and steel that, when used to start a fire, creates a random colored flame.',
        'a blank piece of wet parchment that never seems to dry.',
        'a small puzzle box made of brass that is slightly warm to the touch.',
        'a cloudy chunk of glass that is said to hold a spark of breath from a blue dragon.',
        'a crude chalice made of coal.',
        'a miniature brass horn, silent when played, but fills the air with the scent of warm and exotic spices.',
        'an eye-sized blue pearl that floats in salt water.',
        'a tuning fork made from a dark metal which glows with a pale, white light during thunderstorms.',
        'a small vial that is always filled with the smell of autumn wind.',
        'a clear marble that slowly rolls toward the nearest source of running water.',
        'a small collapsible silver cup that perspires constantly when opened.',
        'an hourglass that tells time with falling mist instead of sand.',
        'an ornate razor, which only cuts in freezing cold temperature.',
        'a shark tooth covered in tiny etched words from a lost language.',
        'a large brass coin with no markings or images in it.',
        'a small wooden box filled with a strange red clay.',
        'a necklace with a small, rusted iron anchor.',
        'a small brass flute adorned with silver wire that is always faintly sounding.',
        'a red and black aarakocra feather.',
        'a palm-size stone with a hole in it, through which can be heard a constantly whispering wind.',
        'a small conch shell covered in black crystal.',
        'a small music box made of brass, it features a pair of tiny automations that resemble azer working at a forge.',
        'a glass jar containing the preserved corpse of an unfamiliar aquatic creature.',
        'a piece of petrified wood carved into the shape of a seashell.',
        'a wooden puzzle cube covered in elemental symbols.',
        'a small stone cube that acts as a magnet when placed against another stone.',
        'a ring made of a white metal, on the inside is a name etched in Auran.',
        'a bracelet made of silvered fish hooks.',
        'a journal filled with poetry hand-written in Primordial.',
        'a yellow gemstone that glows dimly when a storm is nearby.',
        'a charred chisel with an unfamiliar symbol stamped into its base.',
        'a canteen filled with a foul smelling orange mud.',
        'a faceless doll made of driftwood.',
        'a heavy iron key bearing the name of a ship long lost to the sea.',
        'a small jewelry box made from the shell of a turtle.',
        'a chess piece fashioned to look like fire myrmidon.',
        'a spinning top with an image of one of the four elements on each side.',
        'a single hoop earring made of a porous red stone.',
        'an arrowhead carved from seasalt.',
        'a small comb made of blue coral.',
        'seven small beads of sandstone on a string, all different colors.',
        'a romance chapbook written in undercommon titled “Just One Layer of Grey”.',
        'A tiny, broken clockwork harpy.',
        'an ivory whale statuette.',
        'a fist-sized cog, covered in barnacles.',
        'an eyepatch made of obsidian and a black leather cord.',
        'a glass bottle with a tiny ship of unfamiliar design inside'
    ],
    cos: [
        'a picture you drew as a child of your imaginary friend.',
        'a lock that opens when blood is dripped in its keyhole.',
        'clothes stolen from a scarecrow.',
        'a spinning top carved with four faces: happy, sad, wrathful and dead.',
        'the necklace of a sibling who died on the day you were born.',
        'a wig from someone executed by beheading.',
        'the unopened letter to you from your dying father.',
        'a pocket watch that runs backward for an hour every midnight.',
        'a winter coat stolen from a dying soldier.',
        'a bottle of invisible ink that can only be read at sunset.',
        'a wineskin that refills when interred with a dead person for a night.',
        'a set of silverware used by a king for his last meal.',
        'a spyglass that always shows the world suffering from a terrible storm.',
        'a cameo with the profile’s face scratched away.',
        'a lantern with a black candle that never runs out and that burns with a green flame.',
        'a teacup from a child’s tea set, stained with blood.',
        'a little black book that records your dreams when you sleep.',
        'a necklace formed from the interlinked holy symbols of a dozen deities, a hangman’s noose that feels heavier than it should.',
        'a birdcage into which small birds fly but once inside never eat or leave.',
        'a lepidopterist’s box filled with dead moths with skull-like patterns on their wings.',
        'a jar of pickled ghouls’ tongues.',
        'the wooden hand of a notorious pirate.',
        'an urn with the ashes of a dead relative.',
        'a hand mirror backed with a bronze depiction of a medusa.',
        'pallid leather gloves crafted with ivory fingernails.',
        'dice made from the knuckles of a notorious charlatan.',
        'a ring of keys for forgotten locks.',
        'nails from the coffin of a murderer.',
        'a key to the family crypt.',
        'a bouquet of funerary flowers that always looks and smells fresh.',
        'a switch used to discipline you as a child.',
        'a music box that plays by itself whenever someone holding it dances.',
        'a walking cane with an iron ferule that strikes sparks on stone.',
        'a flag from a ship lost at sea.',
        'a porcelain doll’s head that always seems to be looking at you.',
        'a wolf’s head wrought in silver that is also a whistle.',
        'a small mirror that shows a much older version of the viewer.',
        'a small, worn book of children’s nursery rhymes.',
        'a mummified raven claw.',
        'a broken pendant of a silver dragon that’s always cold to the touch.',
        'a small locked box that quietly hums a lovely melody at night which you forget in the morning.',
        'an inkwell that makes one a little nauseous when staring at it.',
        'a little old doll made from a dark, dense wood and missing a hand and a foot.',
        'a black executioner’s hood.',
        'a pouch made of flesh, with a sinew drawstring.',
        'a tiny spool of black thread that never runs out.',
        'a tiny clockwork figurine of a dancer that’s missing a gear and doesn’t work.',
        'a black wooden pipe that creates puffs of smoke that look like skulls.',
        'a vial of perfume, the scent of which only certain creatures can detect'
    ],
    llok: [
        'a handheld device containing a glowing green gem that darkens when no oxygen is present.',
        'a foot-long, egg-shaped object made from stitched leather.',
        'a black metal cylinder that dictates the history of an unknown plant or animal species when held.',
        'a cylindrical jar containing a pickled crustacean of unknown origin.',
        'a small thumb-button storage cylinder that releases a useless iron key when pressed.',
        'an unusual heraldic cloak pin that emits a short musical fanfare when tapped.',
        'a handheld tube that sucks in dust when squeezed and captures it in a detachable compartment.',
        'a scintillating disk of unknown material.',
        'a dial that can be twisted to slowly click back to its origin, whereupon it emits a loud ringing noise.',
        'a hovering, apple-sized orb of metal that follows you around.',
        'the petrified cocoon of an unknown insect.',
        'a bronze gauntlet set with many slots, and which violently expels any object pressed into those slots.',
        'a box that plays an illusory message in an unknown language when opened.',
        'a rod that causes you to forget the last five minutes when you press a button near its tip.',
        'a palm-sized cylinder that emits a harmless ray of glowing blue light when squeezed.',
        'a bead that suppresses your hearing when secreted inside either ear, causing you to be deafened.',
        'an amulet that displays your current health as a green bar above your head, with the bar retracting as your hit point total decreases.',
        'a casket containing one hundred tasteless blue pills that produce no discernible effect when swallowed.',
        'a metal mechanical puzzle with no apparent solution.',
        'a metal spinning top that never tips over when spun.',
        'two strips of cloth-like material, each coated with a soft, hair-like fuzz on one side.',
        'a simple wire pyramid that preserves any foodstuff it is placed over.',
        'a star chart labeled in an unknown script.',
        'a rectangle of black glass that displays indecipherable arcane runes when you swipe your finger across it.',
        'a schematic that shows the inner workings of an impossibly complex device.',
        'an odd pair of comfortable shoes made from supple, multicolored material.',
        'a mirror that makes you appear more beautiful when you tap your reflection.',
        'a mechanical metal puppy that playfully follows you when activated.',
        'a talking bracelet that speaks only to correct your grammar.',
        'a bar of soap that can remove any stain.',
        'a journal in Common, written by someone in a world similar to but not quite the same as your own.',
        'a tub containing one serving of disgusting but nutritious goop that refills itself slowly over the course of one week.',
        'an instruction manual for activating a mysterious, world-destroying device.',
        'a small supple disk that displays weird moving symbols when placed over either eye.',
        'a tiny desk set with large, colorful buttons, each of which plays a discordant musical fanfare when pressed.',
        'a pair of tinted spectacles that reduce the glare of the sun when worn.',
        'an inflatable bedroll made from an unknown material, and which slowly deflates when used.',
        'a rod tipped with a blunt metal pincer whose grip can be adjusted by turning a screw.',
        'a battered helmet with a transparent orange visor that flips into place when donned.',
        'an animated map of a mysterious city that appears to be tracking the movements of five creatures.',
        'a cylinder of mist that holds your hair perfectly in shape when sprayed onto your head.',
        'a talking wand that tells you the name of any plant you point it at.',
        'a metal bracelet that displays the number of steps you’ve taken since your last long rest.',
        'a tiny handheld device that projects a glowing dot onto whatever you point it at.',
        'a rectangular piece of glass that displays a twelve-digit countdown on its surface.',
        'a wall chart of mysterious formulae arranged into a color-coded grid.',
        'a handheld device that solves any math problem you input using its buttons.',
        'a ball of speckled fur that appears to be alive.',
        'a complicated crystal board game that you don’t know how to play.',
        'a large glass rectangle that displays a storm of black and white patterns when you press a button on its underside'
    ]
};
